"""
Specific error codes to raise
"""

NOT_AUTHENTICATED = "not_authenticated"
INVALID_INPUT_DATA = "invalid_input_data"
INVALID_OTP = "invalid_otp"
NOT_FOUND = "not_found"
OTP_RESEND_TIME_LIMIT = "otp_resend_time_limit"
TOO_MANY_REQUEST = "too_many_request"
INTERNAL_SERVER_ERROR = "internal_server_error"
ACCESS_DENIED = "access_denied"
TOKEN_EXPIRED = "token_expired"
USER_INACTIVE = "user_inactive"
INVALID_REFRESH_TOKEN = "invalid_refresh_token"
USER_ALREADY_EXISTS = "user_already_exists"
USER_NOT_FOUND = "user_not_found"
USER_NOT_AUTHORIZED = "user_not_authorized"
USER_DOES_NOT_HAVE_PHONE_NUMBER = "user_does_not_have_phone_number"
PASSWORD_MIN_LENGTH = "password_min_length"
PASSWORDS_ARE_NOT_EQUAL = "passwords_are_not_equal"
PASSWORD_INVALID = "password_invalid"
EMAIL_CONFIRMATION_EXPIRED = "email_confirmation_expired"
EMAIL_ALREADY_CONFIRMED = "email_already_confirmed"
CLUB_BRANCH_NOT_FOUND = "club_branch_not_found"
COMPUTER_DOES_NOT_BELONG_TO_CLUB_BRANCH = "computer_does_not_belong_to_club_branch"
COMPUTER_IS_ALREADY_BOOKED = "COMPUTER_IS_ALREADY_BOOKED"
GIZMO_REQUEST_ERROR = "gizmo_request_error"
