# Generated by Django 4.1.7 on 2023-07-03 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuterServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('service', models.CharField(max_length=255, verbose_name='Класс')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Данные')),
                ('status', models.CharField(choices=[('NO_REQUEST', 'Не было запроса'), ('WAS_REQUEST', 'Был запрос'), ('REQUEST_ERROR', 'Ошибка запроса'), ('SERVICE_UNAVAILABLE', 'Сервис не доступен')], default='NO_REQUEST', max_length=255, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата запроса')),
                ('runtime', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Выполнено за(сек)')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'История запросов',
                'verbose_name_plural': 'Сервисы: История запросов',
            },
        ),
        migrations.RenameModel(
            old_name='ServiceResponse',
            new_name='OuterServiceResponse',
        ),
        migrations.DeleteModel(
            name='ServiceHistory',
        ),
        migrations.AlterField(
            model_name='outerserviceresponse',
            name='history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_response', to='integrations.outerservicelog', verbose_name='Лог'),
        ),
    ]
