# Generated by Django 4.1.7 on 2023-04-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcomputer',
            name='hall_type',
            field=models.CharField(choices=[('STANDARD', 'Стандарт'), ('VIP', 'ВИП')], default='STANDARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='clubcomputer',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
