# Generated by Django 4.1.7 on 2023-05-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_rename_clubuserinfo_clubbranchuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranchuser',
            name='gizmo_id',
            field=models.IntegerField(null=True),
        ),
    ]
