# Generated by Django 4.1.7 on 2023-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubbranchuser_gizmo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbranchuser',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
