# Generated by Django 4.1.7 on 2023-05-01 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_alter_clubbranchuser_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubComputerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('club_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computer_groups', to='clubs.clubbranch')),
            ],
        ),
        migrations.AddField(
            model_name='clubcomputer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='clubs.clubcomputergroup'),
        ),
    ]
