# Generated by Django 4.1.7 on 2023-05-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_clubcomputergroup_clubcomputer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcomputergroup',
            name='gizmo_id',
            field=models.IntegerField(null=True),
        ),
    ]
