# Generated by Django 4.1.7 on 2023-05-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_clubcomputergroup_gizmo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranch',
            name='gizmo_payment_method',
            field=models.IntegerField(default=2),
        ),
    ]
