# Generated by Django 4.1.7 on 2023-05-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_clubbranchhardware_group_clubbranchprice_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubbranchhardware',
            name='hall_type',
        ),
        migrations.RemoveField(
            model_name='clubbranchprice',
            name='hall_type',
        ),
        migrations.RemoveField(
            model_name='clubbranchproperty',
            name='hall_type',
        ),
        migrations.RemoveField(
            model_name='clubcomputer',
            name='hall_type',
        ),
    ]
