# Generated by Django 4.1.7 on 2023-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_remove_clubbranchhardware_hall_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranch',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
