# Generated by Django 4.1.7 on 2023-05-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_clubbranch_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranchuser',
            name='gizmo_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
