# Generated by Django 4.1.7 on 2023-05-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_clubbranchuser_gizmo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbranchhardware',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.clubcomputergroup'),
        ),
        migrations.AlterField(
            model_name='clubbranchprice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.clubcomputergroup'),
        ),
        migrations.AlterField(
            model_name='clubbranchproperty',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.clubcomputergroup'),
        ),
    ]
