# Generated by Django 4.1.7 on 2023-05-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0016_rename_ip_address_clubbranch_api_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbranchuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
