# Generated by Django 4.1.7 on 2023-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_alter_clubbranchuser_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubbranch',
            options={'ordering': ['id'], 'verbose_name': 'Филиал Клуба', 'verbose_name_plural': 'Филиалы Клубов'},
        ),
        migrations.AlterModelOptions(
            name='clubcomputer',
            options={'ordering': ['number'], 'verbose_name': 'Компьютер клуба', 'verbose_name_plural': 'Компьютеры клуба'},
        ),
        migrations.AlterField(
            model_name='clubbranchuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
