# Generated by Django 4.1.7 on 2023-07-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_alter_clubbranch_options_alter_clubcomputer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
