# Generated by Django 4.1.7 on 2023-09-30 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_rename_is_booked_clubcomputer_is_active_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTimePacketGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gizmo_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('club_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packet_groups', to='clubs.clubbranch')),
            ],
        ),
        migrations.CreateModel(
            name='ClubTimePacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gizmo_id', models.IntegerField(null=True)),
                ('gizmo_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('minutes', models.IntegerField(default=0)),
                ('packet_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='clubs.clubtimepacketgroup')),
            ],
        ),
    ]
