# Generated by Django 4.1.7 on 2023-09-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0023_alter_clubtimepacket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtimepacketgroup',
            name='computer_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packet_group', to='clubs.clubcomputergroup'),
        ),
    ]
