# Generated by Django 4.1.7 on 2023-09-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_clubtimepacketgroup_computer_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='clubtimepacket',
            name='available_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubtimepacket',
            name='available_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clubtimepacket',
            name='available_days',
            field=models.ManyToManyField(blank=True, null=True, related_name='time_packets', to='clubs.daymodel'),
        ),
    ]
