# Generated by Django 4.1.7 on 2023-09-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_daymodel_clubtimepacket_available_time_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daymodel',
            options={'ordering': ['number'], 'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
    ]
