# Generated by Django 4.1.7 on 2023-11-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_alter_daymodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbranchuser',
            name='gizmo_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='clubbranchuser',
            name='gizmo_phone',
            field=models.CharField(db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='clubcomputer',
            name='gizmo_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
