# Generated by Django 4.1.7 on 2023-12-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_club_is_bro_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranchuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
