# Generated by Django 4.1.7 on 2023-12-28 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_clubbranchuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtimepacket',
            name='club_computer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_packets_group', to='clubs.clubcomputergroup'),
        ),
    ]
