# Generated by Django 4.1.7 on 2024-01-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_clubbranchadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubbranchadmin',
            options={'verbose_name': 'Админ в телеге', 'verbose_name_plural': 'Админы в телеге'},
        ),
        migrations.AlterModelOptions(
            name='clubbranchuser',
            options={'verbose_name': 'Юзер в гизмо', 'verbose_name_plural': 'Юзеры в гизмо'},
        ),
        migrations.AlterModelOptions(
            name='clubcomputergroup',
            options={'verbose_name': 'Зал клубов', 'verbose_name_plural': 'Залы клубов'},
        ),
        migrations.AddField(
            model_name='clubbranchadmin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
