# Generated by Django 4.1.7 on 2024-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_alter_clubbranchadmin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Клуб', 'verbose_name_plural': 'Клубы'},
        ),
        migrations.AddField(
            model_name='club',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
