# Generated by Django 4.1.7 on 2024-02-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_clubbranchlegalentity_clubbranch_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcomputer',
            name='is_broken',
            field=models.BooleanField(default=False),
        ),
    ]
