# Generated by Django 4.1.7 on 2024-02-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_clubbranch_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranch',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
