# Generated by Django 4.1.7 on 2024-05-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0038_clubbranch_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubbranchlegalentity',
            options={'verbose_name': 'ИПшка', 'verbose_name_plural': 'ИПшки'},
        ),
        migrations.AddField(
            model_name='clubbranch',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
