# Generated by Django 4.1.7 on 2024-05-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0039_alter_clubbranchlegalentity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbranchuser',
            name='gizmo_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
