# Generated by Django 4.1.7 on 2024-05-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_alter_clubbranchuser_gizmo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranch',
            name='is_turned_on',
            field=models.BooleanField(default=True),
        ),
    ]
