# Generated by Django 4.1.7 on 2024-05-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_country_city'),
        ('clubs', '0041_clubbranch_is_turned_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_branches', to='common.city'),
        ),
    ]
