# Generated by Django 4.1.7 on 2024-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0042_clubbranch_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcomputer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
