# Generated by Django 4.1.7 on 2024-07-01 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0043_clubcomputer_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubUserCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_amount', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cashbacks', to='clubs.club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
