# Generated by Django 4.1.7 on 2024-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0044_clubusercashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranch',
            name='gizmo_points_method',
            field=models.IntegerField(default=-4),
        ),
    ]
