# Generated by Django 4.1.7 on 2024-08-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0045_clubbranch_gizmo_points_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcomputergroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
