# Generated by Django 4.1.7 on 2024-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0045_clubbranch_gizmo_points_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='software',
            field=models.CharField(choices=[('Senet', 'Senet'), ('Gizmo', 'Gizmo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clubbranch',
            name='outer_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Внешний ID точки в системе партнера'),
        ),
    ]
