# Generated by Django 4.1.7 on 2024-08-03 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0046_club_software_clubbranch_outer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='software',
            new_name='software_type',
        ),
    ]
