# Generated by Django 4.1.7 on 2024-08-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0047_rename_software_club_software_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubcomputergroup',
            old_name='gizmo_id',
            new_name='outer_id',
        ),
    ]
