# Generated by Django 4.1.7 on 2024-08-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0048_rename_gizmo_id_clubcomputergroup_outer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubcomputer',
            old_name='gizmo_id',
            new_name='outer_id',
        ),
    ]
