# Generated by Django 4.1.7 on 2024-08-12 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0021_booking_use_cashback'),
        ('clubs', '0048_clubbranchuser_created_at_clubbranchuser_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedTimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delayed_time_set', to='bookings.booking')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delayed_times', to='clubs.club')),
                ('time_packet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delayed_time_set', to='clubs.clubtimepacket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delayed_time_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
