# Generated by Django 4.1.7 on 2024-08-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0049_delayedtimesetting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubperk',
            unique_together={('club', 'code')},
        ),
    ]
