# Generated by Django 4.1.7 on 2024-08-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0050_rename_gizmo_hostname_clubcomputer_outer_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubcomputer',
            name='outer_hostname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
