# Generated by Django 4.1.7 on 2024-08-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0050_alter_clubperk_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubComputerLayoutGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('outer_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('club_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_groups', to='clubs.clubbranch')),
            ],
        ),
        migrations.AddField(
            model_name='clubcomputer',
            name='layout_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='clubs.clubcomputerlayoutgroup'),
        ),
    ]
