# Generated by Django 4.1.7 on 2024-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0051_alter_clubcomputer_outer_hostname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubbranchuser',
            old_name='gizmo_id',
            new_name='outer_id',
        ),
        migrations.RenameField(
            model_name='clubbranchuser',
            old_name='gizmo_phone',
            new_name='outer_phone',
        ),
        migrations.AlterField(
            model_name='club',
            name='software_type',
            field=models.CharField(choices=[('SENET', 'SENET'), ('GIZMO', 'GIZMO')], max_length=20, null=True),
        ),
    ]
