# Generated by Django 4.1.7 on 2024-08-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0051_clubcomputerlayoutgroup_clubcomputer_layout_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubcomputerlayoutgroup',
            options={'verbose_name': 'Layout Group', 'verbose_name_plural': 'Layout Groups'},
        ),
        migrations.RenameField(
            model_name='clubcomputerlayoutgroup',
            old_name='is_deleted',
            new_name='is_available',
        ),
    ]
