# Generated by Django 4.1.7 on 2024-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0052_alter_clubcomputerlayoutgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtimepacket',
            name='available_days',
            field=models.ManyToManyField(related_name='time_packets', to='clubs.daymodel'),
        ),
    ]
