# Generated by Django 4.1.7 on 2024-09-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0052_alter_clubcomputerlayoutgroup_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubbranchuser',
            old_name='gizmo_id',
            new_name='outer_id',
        ),
        migrations.RenameField(
            model_name='clubbranchuser',
            old_name='gizmo_phone',
            new_name='outer_phone',
        ),
        migrations.RenameField(
            model_name='clubcomputer',
            old_name='gizmo_id',
            new_name='outer_id',
        ),
        migrations.RenameField(
            model_name='clubcomputergroup',
            old_name='gizmo_id',
            new_name='outer_id',
        ),
        migrations.RemoveField(
            model_name='clubcomputer',
            name='gizmo_hostname',
        ),
        migrations.RemoveField(
            model_name='clubcomputergroup',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='club',
            name='software_type',
            field=models.CharField(choices=[('SENET', 'SENET'), ('GIZMO', 'GIZMO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clubbranch',
            name='outer_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Внешний ID точки в системе партнера'),
        ),
        migrations.AddField(
            model_name='clubcomputer',
            name='outer_hostname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
