# Generated by Django 4.1.7 on 2024-10-28 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0053_alter_clubtimepacket_available_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranchuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_club_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
