# Generated by Django 4.1.7 on 2024-09-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0053_rename_gizmo_id_clubbranchuser_outer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranch',
            name='cashbox_password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пароль для кассы филиала'),
        ),
        migrations.AddField(
            model_name='clubbranch',
            name='cashbox_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Логин для кассы филиала'),
        ),
        migrations.AddField(
            model_name='clubbranch',
            name='main_club_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siblings', to='clubs.clubbranch', verbose_name='Основной филиал'),
        ),
    ]
