# Generated by Django 4.1.7 on 2024-11-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0054_clubbranchuser_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbranchadmin',
            name='club_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_admins', to='clubs.clubbranch'),
        ),
    ]
