# Generated by Django 4.1.7 on 2024-10-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0054_clubbranch_cashbox_password_clubbranch_cashbox_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubtimepacket',
            old_name='gizmo_id',
            new_name='outer_id',
        ),
        migrations.RenameField(
            model_name='clubtimepacket',
            old_name='gizmo_name',
            new_name='outer_name',
        ),
    ]
