# Generated by Django 4.1.7 on 2024-10-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0055_rename_gizmo_id_clubtimepacket_outer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtimepacket',
            name='packet_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='clubs.clubtimepacketgroup'),
        ),
    ]
