# Generated by Django 4.1.7 on 2024-11-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0055_alter_clubbranchadmin_club_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbranchuser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
