# Generated by Django 4.1.7 on 2024-10-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0056_alter_clubtimepacket_packet_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtimepacket',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_packets', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='clubtimepacket',
            name='club_computer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_packets', to='clubs.clubcomputergroup'),
        ),
        migrations.AlterField(
            model_name='clubtimepacket',
            name='minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
