# Generated by Django 4.1.7 on 2024-10-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0057_clubtimepacket_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubcomputergroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
