# Generated by Django 4.1.7 on 2024-10-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0053_alter_clubtimepacket_available_days'),
        ('clubs', '0058_clubcomputergroup_is_deleted'),
    ]

    operations = [
    ]
