# Generated by Django 4.1.7 on 2024-11-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0056_alter_clubbranchuser_first_name'),
        ('clubs', '0059_merge_20241028_1503'),
    ]

    operations = [
    ]
