# Generated by Django 4.1.7 on 2024-12-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0061_rename_gizmo_id_clubtimepacketgroup_outer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubtimepacket',
            name='price_for_holidays',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена праздничного дня'),
        ),
        migrations.AddField(
            model_name='clubtimepacket',
            name='use_holiday_price',
            field=models.BooleanField(default=False, verbose_name='Использовать цену праздничного дня'),
        ),
    ]
