# Generated by Django 4.1.7 on 2024-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0062_clubtimepacket_price_for_holidays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubtimepacket',
            name='use_holiday_price',
        ),
        migrations.AddField(
            model_name='clubbranch',
            name='use_holiday_price',
            field=models.BooleanField(default=False, verbose_name='Использовать цену праздничного дня'),
        ),
    ]
