# Generated by Django 4.1.7 on 2024-12-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0063_remove_clubtimepacket_use_holiday_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbranchuser',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clubbranchuser',
            name='outer_phone',
            field=models.CharField(db_index=True, max_length=12, null=True, verbose_name='Номер телефона'),
        ),
    ]
