# Generated by Django 4.1.7 on 2025-01-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0064_alter_clubbranchuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Логотип'),
        ),
    ]
