# Generated by Django 4.1.7 on 2025-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0065_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranchlegalentity',
            name='bin',
            field=models.CharField(default='', max_length=12),
        ),
    ]
