# Generated by Django 4.1.7 on 2025-01-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0066_clubbranchlegalentity_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbranchlegalentity',
            name='bin',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.CreateModel(
            name='ClubBranchPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('club_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_branch_perks', to='clubs.clubbranch')),
            ],
            options={
                'unique_together': {('club_branch', 'code')},
            },
        ),
    ]
