# Generated by Django 4.1.7 on 2025-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0067_alter_clubbranchlegalentity_bin_clubbranchperk'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubbranch',
            name='seating_plan',
            field=models.JSONField(blank=True, help_text='JSON-массив с координатами и номерами компьютеров', null=True, verbose_name='Рассадка компьютеров'),
        ),
    ]
