# Generated by Django 4.1.7 on 2023-06-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_depositreplenishment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('outer_id', models.CharField(max_length=16, unique=True, verbose_name='ID в платежной системе')),
                ('status', models.CharField(choices=[('0', 'Транзакция Создана'), ('1', 'Захолдированы средства'), ('2', 'Разхолдированы средства'), ('3', 'Оплчено'), ('4', 'Возвращено'), ('8', 'В обработке'), ('99', 'Ошибка')], default='0', max_length=20)),
                ('status_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма заказа')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Сумма коммиссии')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('status', models.CharField(choices=[('0', 'Транзакция Создана'), ('1', 'Захолдированы средства'), ('2', 'Разхолдированы средства'), ('3', 'Оплчено'), ('4', 'Возвращено'), ('8', 'В обработке'), ('99', 'Ошибка')], default='0', max_length=256)),
                ('status_reason', models.TextField(blank=True, null=True, verbose_name='Причина присвоения статуса')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='payments.payment')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('pay_token', models.CharField(max_length=255, unique=True, verbose_name='Токен карты в платежной системе')),
                ('is_current', models.BooleanField(default=False)),
                ('card_type', models.CharField(blank=True, max_length=256, null=True)),
                ('first_numbers', models.CharField(blank=True, max_length=6, null=True)),
                ('last_numbers', models.CharField(blank=True, max_length=6, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платежная карта',
                'verbose_name_plural': 'Платежные карты',
            },
        ),
    ]
