# Generated by Django 4.1.7 on 2023-06-25 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('transaction_id', models.CharField(max_length=16, verbose_name='ID в платежной системе')),
                ('booking_uuid', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID в платежной системе')),
                ('data', models.JSONField(verbose_name='Данные')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_history', to='payments.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
