# Generated by Django 4.1.7 on 2023-06-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentwebhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcard',
            name='pay_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен карты в платежной системе'),
        ),
    ]
