# Generated by Django 4.1.7 on 2023-07-08 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_depositreplenishment_booking_and_more'),
        ('payments', '0005_alter_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='replenishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='bookings.depositreplenishment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking'),
        ),
    ]
