# Generated by Django 4.1.7 on 2024-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='outer_id',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='ID в платежной системе'),
        ),
    ]
