# Generated by Django 4.1.7 on 2024-10-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_outer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('ONE_VISION', 'ONE_VISION'), ('KASPI', 'KASPI')], default='ONE_VISION', max_length=20),
        ),
    ]
