# Generated by Django 4.1.7 on 2023-07-02 09:59

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('file', models.FileField(storage=apps.common.utils.OverwriteStorage(), upload_to='documents')),
            ],
        ),
    ]
