# Generated by Django 4.1.7 on 2023-07-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
