# Generated by Django 4.1.7 on 2024-04-12 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_document_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('number', models.IntegerField()),
                ('platform', models.CharField(choices=[('IOS', 'IOS'), ('ANDROID', 'ANDROID')], max_length=10)),
                ('app', models.CharField(choices=[('BRO', 'BRO'), ('Lobby', 'Lobby')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
