# Generated by Django 4.1.7 on 2024-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_appversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handledexception',
            name='code',
            field=models.CharField(max_length=512, verbose_name='Код ошибки'),
        ),
        migrations.AlterField(
            model_name='handledexception',
            name='message',
            field=models.CharField(max_length=512, verbose_name='Описание ошибки'),
        ),
    ]
