# Generated by Django 4.1.7 on 2024-06-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_country_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': '* Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': '* Страны'},
        ),
    ]
