# Generated by Django 4.1.7 on 2023-06-23 17:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outer_payer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID юзера в платежной системе'),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, null=True, verbose_name='Секретный ключ'),
        ),
    ]
