# Generated by Django 4.1.7 on 2023-06-23 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Секретный ключ'),
        ),
    ]
