# Generated by Django 4.1.7 on 2023-10-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_alter_daymodel_options'),
        ('users', '0005_user_club_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='club_branch',
        ),
        migrations.AddField(
            model_name='user',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='clubs.club'),
        ),
    ]
