# Generated by Django 4.1.7 on 2024-01-21 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_alter_club_options_club_code'),
        ('users', '0006_remove_user_club_branch_user_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOneVisionPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID юзера в платежной системе')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onevision_payers', to='clubs.club')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onevision_payers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
