# Generated by Django 4.1.7 on 2024-02-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_clubbranchlegalentity_clubbranch_trader'),
        ('users', '0007_useronevisionpayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='outer_payer_id',
        ),
        migrations.RemoveField(
            model_name='useronevisionpayer',
            name='club',
        ),
        migrations.AddField(
            model_name='useronevisionpayer',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onevision_payers', to='clubs.clubbranchlegalentity'),
        ),
    ]
