# Generated by Django 4.1.7 on 2024-03-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_outer_payer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mobile_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
