# Generated by Django 4.1.7 on 2024-11-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0055_alter_clubbranchadmin_club_branch'),
        ('users', '0010_userperk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='club',
        ),
        migrations.AddField(
            model_name='user',
            name='club_branches',
            field=models.ManyToManyField(blank=True, related_name='admins', to='clubs.clubbranch'),
        ),
    ]
