# Generated by Django 4.1.7 on 2024-10-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userperk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
