# Generated by Django 4.1.7 on 2024-10-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя'),
        ),
    ]
