# Generated by Django 4.1.7 on 2024-10-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_otp',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Последний успешный OTP'),
        ),
    ]
