# Generated by Django 4.1.7 on 2024-11-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_club_user_club_branches'),
        ('users', '0013_user_last_otp'),
    ]

    operations = [
    ]
