# Generated by Django 4.1.7 on 2025-01-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0064_alter_clubbranchuser_first_name_and_more'),
        ('users', '0014_merge_20241126_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_club_branches',
            field=models.ManyToManyField(blank=True, to='clubs.clubbranch', verbose_name='Любимые филиалы клубов'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_clubs',
            field=models.ManyToManyField(blank=True, to='clubs.club', verbose_name='Любимые клубы'),
        ),
    ]
