# Generated by Django 4.1.7 on 2023-05-20 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0018_alter_clubbranch_options_alter_clubcomputer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('status', models.CharField(choices=[('IN_PROCESS', 'В обработке'), ('DECLINED', 'Отклонено'), ('CANCELLED', 'Отменено'), ('ACCEPTED', 'Принято')], default='IN_PROCESS', max_length=20)),
                ('use_balance', models.BooleanField(default=False)),
                ('club_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clubs.clubbranch')),
                ('club_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='clubs.clubbranchuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='bookings.booking')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clubs.clubcomputer')),
            ],
        ),
    ]
