# Generated by Django 4.1.7 on 2023-05-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='use_balance',
            field=models.BooleanField(default=True),
        ),
    ]
