# Generated by Django 4.1.7 on 2023-05-27 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_alter_clubbranch_options_alter_clubcomputer_options_and_more'),
        ('bookings', '0002_booking_amount_alter_booking_use_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositReplenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('gizmo_id', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('club_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_replenishments', to='clubs.clubbranch')),
                ('club_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replenishments', to='clubs.clubbranchuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
