# Generated by Django 4.1.7 on 2023-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_depositreplenishment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Бронь принята'), ('PLAYING', 'Юзер играет'), ('COMPLETED', ''), ('CANCELLED', 'Отменено')], default='ACCEPTED', max_length=20),
        ),
    ]
