# Generated by Django 4.1.7 on 2023-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_commission_amount_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositreplenishment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='depositreplenishment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
