# Generated by Django 4.1.7 on 2023-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_depositreplenishment_commission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Бронь принята'), ('SESSION_STARTED', 'Тарификация началась'), ('PLAYING', 'Юзер играет'), ('COMPLETED', 'Зевершено'), ('CANCELLED', 'Отменено')], default='ACCEPTED', max_length=20),
        ),
    ]
