# Generated by Django 4.1.7 on 2023-08-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='platform',
            field=models.CharField(choices=[('WEB', 'WEB'), ('PHYSICAL', 'PHYSICAL')], default='WEB', max_length=256),
        ),
    ]
