# Generated by Django 4.1.7 on 2023-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_starting_session',
            field=models.BooleanField(default=False),
        ),
    ]
