# Generated by Django 4.1.7 on 2023-09-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_alter_daymodel_options'),
        ('bookings', '0014_booking_is_starting_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_packet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='clubs.clubtimepacket'),
        ),
    ]
