# Generated by Django 4.1.7 on 2023-10-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_booking_time_packet'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositreplenishment',
            name='cashback_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
