# Generated by Django 4.1.7 on 2023-11-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_depositreplenishment_cashback_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.RenameField(
            model_name='depositreplenishment',
            old_name='amount',
            new_name='user_received_amount',
        ),
    ]
