# Generated by Django 4.1.7 on 2024-04-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_depositreplenishment_time_packet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Бронь принята'), ('SESSION_STARTED', 'Тарификация началась'), ('PLAYING', 'Юзер играет'), ('COMPLETED', 'Зевершено'), ('CANCELLED', 'Отменено'), ('EXPIRED', 'Истекло')], default='ACCEPTED', max_length=20),
        ),
    ]
