# Generated by Django 4.1.7 on 2024-11-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_booking_is_time_packet_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositreplenishment',
            old_name='gizmo_id',
            new_name='outer_id',
        ),
    ]
