# Generated by Django 4.1.7 on 2024-12-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0023_rename_gizmo_id_depositreplenishment_outer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='for_free',
            field=models.BooleanField(default=False),
        ),
    ]
