# Generated by Django 4.1.7 on 2024-03-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0038_clubbranch_priority'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGAuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.CharField(max_length=12)),
                ('chat_id', models.IntegerField(max_length=30)),
                ('club_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tg_user', to='clubs.clubbranchuser')),
            ],
        ),
    ]
