# Generated by Django 4.1.7 on 2024-03-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0038_clubbranch_priority'),
        ('authentication', '0002_tgauthuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgauthuser',
            name='club_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tg_user', to='clubs.clubbranchuser'),
        ),
    ]
