# Generated by Django 4.1.7 on 2024-03-11 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_tgauthuser_club_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('mobile_phone', models.CharField(max_length=12)),
                ('otp_code', models.CharField(max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
