# Generated by Django 4.1.7 on 2024-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_verifiedotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgauthuser',
            name='chat_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
