# Generated by Django 4.1.7 on 2024-10-04 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_alter_tgauthuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_logins', to=settings.AUTH_USER_MODEL),
        ),
    ]
