# Generated by Django 4.1.7 on 2024-11-29 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_firebasetoken_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaryqLabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
